name: No Push on Fridays

on:
  push:
    branches:
      - "*"

jobs:
  check_push_day:
    runs-on: ubuntu-latest
    steps:
      - name: Check Day of the Week
        id: check_day
      run: echo "DAY=$(date +'%A')" >> $GITHUB_ENV

      - name: Restrict Push on Fridays
      if: env.DAY == 'Friday'
        run: |
          echo "Pushing code on Fridays is not allowed!"
          exit 1
